 development:
   host: ctis.locomotivehosting.com
   email: dcms.pe@gmail.com
   password: Triptak@1987
   api_key: 85257fb8d52525c6ba739adf11621670dd7647f6
 staging:
   host: ctis.locomotivehosting.com
   email: dcms.pe@gmail.com	
   password: Triptak@1987
   api_key: 85257fb8d52525c6ba739adf11621670dd7647f6
 production:
   host: ctis.locomotivehosting.com
   email: dcms.pe@gmail.com
   password: Triptak@1987
   api_key: 85257fb8d52525c6ba739adf11621670dd7647f6
hosting:
  host: ctis.locomotivehosting.com
  api_key: 85257fb8d52525c6ba739adf11621670dd7647f6
  ssl: true
  email: dcms.pe@gmail.com
  password: Triptak@1987
